import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

const appShell = readFileSync(join(process.cwd(), "components/app-shell.tsx"), "utf8");
const primaryNav = readFileSync(join(process.cwd(), "components/primary-nav.tsx"), "utf8");
const sidebarCommand = readFileSync(join(process.cwd(), "components/sidebar-command.tsx"), "utf8");
const sidebarSearchShortcut = readFileSync(join(process.cwd(), "components/sidebar-search-shortcut.tsx"), "utf8");
const createRecordActions = readFileSync(join(process.cwd(), "lib/create-record-actions.ts"), "utf8");
const contactsPage = readFileSync(join(process.cwd(), "app/contacts/page.tsx"), "utf8");
const dealsPage = readFileSync(join(process.cwd(), "app/deals/page.tsx"), "utf8");
const leadsPage = readFileSync(join(process.cwd(), "app/leads/page.tsx"), "utf8");
const navigation = readFileSync(join(process.cwd(), "lib/navigation.ts"), "utf8");
const organizationsPage = readFileSync(join(process.cwd(), "app/organizations/page.tsx"), "utf8");
const pipelinePage = readFileSync(join(process.cwd(), "app/pipeline/page.tsx"), "utf8");
const quotesPage = readFileSync(join(process.cwd(), "app/quotes/page.tsx"), "utf8");
const globalStyles = readFileSync(join(process.cwd(), "app/globals.css"), "utf8");
const smokeSpec = readFileSync(join(process.cwd(), "tests/browser/smoke.spec.ts"), "utf8");

describe("main navigation visibility", () => {
  it("keeps Settings in the primary navigation and workspace shortcut area", () => {
    expect(appShell).toContain("aria-label=\"Workspace navigation\"");
    expect(appShell).toContain('export { appShellNavigationManifest } from "@/lib/navigation";');
    expect(primaryNav).toContain("appShellNavigationManifest.filter((item) => item.group === group && item.primary !== false)");
    expect(primaryNav).toContain("navigationIcons[item.icon]");
    expect(navigation).toContain("href: \"/settings\"");
    expect(navigation).toContain("label: \"Settings\"");
    expect(navigation).toContain("group: \"System\"");
    expect(primaryNav).toContain("id={`primary-nav-${group.label.toLowerCase()}`}");
    expect(primaryNav).toContain("aria-labelledby={`primary-nav-${group.label.toLowerCase()}`}");
    expect(primaryNav).toContain("const navItemLabel = primaryNavItemLabel(item.label, isActive);");
    expect(primaryNav).toContain("aria-label={navItemLabel}");
    expect(primaryNav).toContain("title={navItemLabel}");
    expect(primaryNav).toContain("href={item.href}");
    expect(primaryNav).toContain("prefetch={true}");
    expect(primaryNav).toContain('className="nav-item-label"');
    expect(primaryNav).toContain("function primaryNavItemLabel(label: string, isActive: boolean)");
    expect(primaryNav).toContain("return isActive ? `Current section: ${label}` : `Go to ${label}`;");
    expect(appShell).toContain("const settingsActionLabel = `Open workspace settings for ${workspace.name}`;");
    expect(appShell).toContain('const switchWorkspaceLabel = "Switch active workspace";');
    expect(appShell).toContain('const signOutActionLabel = "Sign out of Northstar CRM";');
    expect(appShell).toContain("aria-label={switchWorkspaceLabel}");
    expect(appShell).toContain("title={switchWorkspaceLabel}");
    expect(appShell).toContain("sidebar-settings-link");
    expect(appShell).toContain("aria-label={settingsActionLabel}");
    expect(appShell).toContain("title={settingsActionLabel}");
    expect(appShell).toContain("aria-label={signOutActionLabel}");
    expect(appShell).toContain("title={signOutActionLabel}");
    expect(appShell).toContain("Settings");
  });

  it("keeps global search and navigation shortcuts available from the app shell", () => {
    expect(appShell).toContain("<SidebarCommand globalSearchDefaultValue={globalSearchDefaultValue} />");
    expect(sidebarCommand).toContain("export function SidebarCommand");
    expect(sidebarCommand).toContain("\"use client\";");
    expect(sidebarCommand).not.toContain('import { usePathname } from "next/navigation"');
    expect(sidebarCommand).not.toContain("const pathname = usePathname() ?? \"\"");
    expect(sidebarCommand).toContain("sidebar-command");
    expect(sidebarCommand).toContain('const globalActionsLabel = "Global actions"');
    expect(sidebarCommand).toContain("aria-label={globalActionsLabel}");
    expect(sidebarCommand).toContain("title={globalActionsLabel}");
    expect(sidebarCommand).toContain("sidebar-command-header");
    expect(sidebarCommand).toContain("Search and jump without leaving the workspace flow.");
    expect(sidebarCommand).toContain("action=\"/search\"");
    expect(sidebarCommand).toContain('import { useId } from "react"');
    expect(sidebarCommand).toContain("const generatedSearchId = useId()");
    expect(sidebarCommand).toContain("const searchInputId = `${generatedSearchId}-global-search`");
    expect(sidebarCommand).toContain("const searchHelperId = `${generatedSearchId}-sidebar-command-helper`");
    expect(sidebarCommand).toContain("aria-describedby={searchHelperId}");
    expect(sidebarCommand).toContain('const searchFormLabel = "Search workspace records"');
    expect(sidebarCommand).toContain("aria-label={searchFormLabel}");
    expect(sidebarCommand).toContain("title={searchFormLabel}");
    expect(sidebarCommand).toContain('const submitSearchLabel = "Submit workspace search"');
    expect(sidebarCommand).toContain("aria-label={submitSearchLabel}");
    expect(sidebarCommand).toContain("title={submitSearchLabel}");
    expect(sidebarCommand).toContain("role=\"search\"");
    expect(sidebarCommand).toContain("defaultValue={globalSearchDefaultValue}");
    expect(sidebarCommand).toContain("htmlFor={searchInputId}");
    expect(sidebarCommand).toContain("id={searchInputId}");
    expect(sidebarCommand).toContain("type=\"search\"");
    expect(sidebarCommand).toContain("placeholder=\"Search records...\"");
    expect(sidebarCommand).toContain("<SidebarSearchShortcut inputId={searchInputId} />");
    expect(sidebarCommand).toContain("aria-keyshortcuts=\"/ Meta+K Control+K\"");
    expect(sidebarSearchShortcut).toContain("export function SidebarSearchShortcut");
    expect(sidebarSearchShortcut).toContain("inputId = \"global-search\"");
    expect(sidebarSearchShortcut).toContain("window.addEventListener(\"keydown\", onKeyDown)");
    expect(sidebarSearchShortcut).toContain("window.removeEventListener(\"keydown\", onKeyDown)");
    expect(sidebarSearchShortcut).toContain("event.preventDefault()");
    expect(sidebarSearchShortcut).toContain("input.focus()");
    expect(sidebarSearchShortcut).toContain("if (isSlash && isTextEntryTarget(event.target)) return;");
    expect(sidebarSearchShortcut).toContain("if (!isSlash && !isCommandSearch) return;");
    expect(sidebarSearchShortcut).toContain("textEntryTags.has(target.tagName)");
    expect(sidebarCommand).toContain("id={searchHelperId}");
    expect(sidebarCommand).toContain('const quickActionsLabel = "Quick actions"');
    expect(sidebarCommand).toContain("import { ActionGroup }");
    expect(sidebarCommand).toContain('<ActionGroup className="sidebar-quick-actions" label={quickActionsLabel}>');
    expect(sidebarCommand).toContain("sidebarSearchActionIcons[item.icon]");
    expect(sidebarCommand).not.toContain("sidebarJumpNavigationItems.map((item) => ({");
    expect(sidebarCommand).not.toContain("const isActive = quickActionMatchesPathname(pathname, action.href);");
    expect(sidebarCommand).not.toContain("aria-current={isActive ? \"page\" : undefined}");
    expect(sidebarCommand).toContain("aria-label={actionTitle}");
    expect(sidebarCommand).toContain("className=\"sidebar-quick-action\"");
    expect(sidebarCommand).toContain("const actionTitle = `${action.label}: ${action.helper}`");
    expect(sidebarCommand).toContain("title={actionTitle}");
    expect(sidebarCommand).not.toContain("buildSearchCreateActions(globalSearchDefaultValue)");
    expect(sidebarCommand).not.toContain("getCrmCreateActionDefinition(action.href)");
    expect(sidebarCommand).not.toContain("createSidebarHelperForQuery(createMetadata, searchValue)");
    expect(sidebarCommand).not.toContain("sidebarCreateActionIcons");
    expect(sidebarCommand).not.toContain('label: "Create"');
    expect(sidebarCommand).toContain("const findActions = hasSearchValue");
    expect(sidebarCommand).toContain("searchListNavigationItems.map((item) => ({");
    expect(sidebarCommand).toContain("href: queryListHref(item.href, searchValue)");
    expect(sidebarCommand).toContain("helper: sidebarSearchListHelper(item.label, searchValue)");
    expect(sidebarCommand).toContain("function sidebarSearchListHelper(label: string, searchValue: string)");
    expect(sidebarCommand).toContain("return `Find \"${searchValue}\" in ${label.toLowerCase()}`;");
    expect(sidebarCommand).toContain("...(findActions.length > 0 ? [{ label: \"Find\", actions: findActions }] : [])");
    expect(sidebarCommand).toContain("const sidebarQuickActionGroups");
    expect(createRecordActions).toContain("export function createSidebarHelperForQuery");
    expect(createRecordActions).toContain("return `Prefills ${prefillKeyLabels[prefillKey]}`;");
    expect(sidebarCommand).toContain("Open matching list shortcuts for this search.");
    expect(sidebarCommand).toContain("Use page-level New buttons for contacts, organizations, leads, deals, and activities.");
    expect(sidebarCommand).toContain("aria-label=\"Active workspace search\"");
    expect(sidebarCommand).toContain("className=\"sidebar-current-query\"");
    expect(sidebarCommand).toContain("<strong>{searchValue}</strong>");
    expect(sidebarCommand).toContain("const clearSearchActionLabel = hasSearchValue ? clearSearchLabel(searchValue) : \"\"");
    expect(sidebarCommand).toContain("aria-label={clearSearchActionLabel}");
    expect(sidebarCommand).toContain("className=\"sidebar-current-query-clear\"");
    expect(sidebarCommand).toContain("href={\"/search\" as Route}");
    expect(sidebarCommand).toContain("title={clearSearchActionLabel}");
    expect(sidebarCommand).toContain("function clearSearchLabel(searchValue: string)");
    expect(sidebarCommand).toContain("return `Clear workspace search for ${searchValue}`;");
    expect(sidebarCommand).not.toContain("function quickActionMatchesPathname(pathname: string, href: Route)");
    expect(sidebarCommand).not.toContain("const hrefPath = String(href).split(\"?\")[0];");
    expect(sidebarCommand).toContain("sidebar-quick-action-group");
    expect(sidebarCommand).toContain("className=\"sidebar-quick-action-group\" aria-labelledby={headingId} key={group.label} role=\"group\"");
    expect(sidebarCommand).toContain("const headingId = `sidebar-quick-actions-${group.label.toLowerCase()}`");
    expect(sidebarCommand).toContain("aria-labelledby={headingId}");
    expect(sidebarCommand).toContain("id={headingId}");
    expect(sidebarCommand).toContain("sidebar-quick-action-icon");
    expect(createRecordActions).toContain('sidebarHelper: "Opportunity"');
    expect(navigation).toContain("href: \"/email\"");
    expect(navigation).toContain("label: \"Inbox\"");
    expect(navigation).toContain("helper: \"Mailbox + priority\"");
    expect(navigation).toContain("Open synced email, Relationship Inbox priorities, Smart Labels, AI reply drafts, and follow-ups.");
    expect(primaryNav).toContain("pathname === hrefPath || pathname.startsWith(`${hrefPath}/`)");
    expect(navigation).toContain("href: \"/quotes\" as Route");
    expect(navigation).toContain("label: \"Quotes\"");
    expect(navigation).toContain("icon: \"FileText\"");
    expect(navigation).toContain("Review quote snapshots and their related deals.");
    expect(quotesPage).toContain("export default async function QuotesPage");
    expect(quotesPage).toContain("listQuotesPage");
    expect(quotesPage).toContain("resetHref=\"/quotes\"");
    expect(quotesPage).toContain("PaginationControls basePath=\"/quotes\"");
    expect(navigation).not.toContain("label: \"Smart Labels\"");
    expect(navigation).not.toContain("label: \"AI Reply Assistant\"");
    expect(navigation).not.toContain("label: \"Relationship Inbox\"");
    expect(navigation).toContain("helper: \"Command center\"");
    expect(navigation).toContain("helper: \"Deal board\"");
    expect(navigation).toContain("helper: \"List view\"");
    expect(navigation).toContain("helper: \"People\"");
    expect(navigation).toContain("helper: \"Accounts\"");
    expect(navigation).toContain("helper: \"Prospects\"");
    expect(navigation).toContain("helper: \"Work queue\"");
    expect(navigation).toContain("helper: \"Metrics\"");
    expect(navigation).toContain("helper: \"Admin\"");
    expect(navigation).toContain("commandJump: true");
    expect(createRecordActions).toContain('href: "/deals/new"');
    expect(createRecordActions).toContain('prefillKey: "title"');
    expect(createRecordActions).toContain('href: "/contacts/new"');
    expect(createRecordActions).toContain('prefillKey: "name"');
    expect(createRecordActions).toContain('href: "/organizations/new"');
    expect(createRecordActions).toContain('href: "/leads/new"');
    expect(createRecordActions).toContain('href: "/activities/new"');
    expect(createRecordActions).toContain('sidebarLabel: "New deal"');
    expect(createRecordActions).toContain('sidebarLabel: "New contact"');
    expect(createRecordActions).toContain('sidebarLabel: "New organization"');
    expect(createRecordActions).toContain('sidebarLabel: "New lead"');
    expect(createRecordActions).toContain('sidebarLabel: "New activity"');
    expect(navigation).toContain("href: \"/dashboard\"");
    expect(navigation).toContain("href: \"/pipeline\"");
    expect(navigation).toContain("href: \"/deals\"");
    expect(navigation).toContain("href: \"/quotes\" as Route");
    expect(navigation).toContain("href: \"/contacts\"");
    expect(navigation).toContain("href: \"/organizations\"");
    expect(navigation).toContain("href: \"/leads\"");
    expect(navigation).toContain("href: \"/activities\"");
    expect(primaryNav).toContain("aria-current={isActive ? \"page\" : undefined}");
    expect(globalStyles).toContain(".sidebar-search");
    expect(globalStyles).toContain(".sidebar-command-header");
    expect(globalStyles).toContain(".sidebar-command-helper");
    expect(globalStyles).toContain(".sidebar-current-query");
    expect(globalStyles).toContain(".sidebar-current-query-clear");
    expect(globalStyles).toContain(".sidebar-quick-actions");
    expect(globalStyles).toContain(".sidebar-quick-action-grid");
    expect(globalStyles).toContain("grid-template-columns: repeat(auto-fit, minmax(min(100%, 170px), 1fr));");
    expect(globalStyles).toContain(".sidebar-quick-action-icon");
    expect(globalStyles).toContain(".nav-item-label");
    expect(globalStyles).toContain("text-overflow: ellipsis;");
    expect(globalStyles).toContain("white-space: nowrap;");
    expect(globalStyles).toContain("word-break: keep-all;");
    expect(globalStyles).toContain(".nav-item-active::before");
    expect(globalStyles).toContain("background: var(--accent);");
    expect(globalStyles).toContain("overflow-wrap: normal;");
  });

  it("keeps basic create actions on list pages instead of the sidebar command", () => {
    expect(sidebarCommand).not.toContain('label: "Create"');
    expect(sidebarCommand).not.toContain('sidebarLabel: "New contact"');
    expect(sidebarCommand).not.toContain('sidebarLabel: "New organization"');
    expect(sidebarCommand).not.toContain('sidebarLabel: "New lead"');
    expect(contactsPage).toContain('createLabel="New contact"');
    expect(organizationsPage).toContain('createLabel="New organization"');
    expect(leadsPage).toContain('createLabel="New lead"');
    expect(dealsPage).toContain('createLabel="New deal"');
    expect(pipelinePage).toContain('createLabel="New deal"');
  });

  it("prevents the fixed desktop sidebar from hiding lower navigation items", () => {
    expect(globalStyles).toContain(".sidebar {\n  position: sticky;");
    expect(globalStyles).toContain("display: flex;");
    expect(globalStyles).toContain("flex-direction: column;");
    expect(globalStyles).toContain("overflow-y: auto;");
    expect(globalStyles).toContain(".sidebar nav");
    expect(globalStyles).toContain("flex-shrink: 0;");
    expect(globalStyles).toContain("overflow: visible;");
    expect(globalStyles).toContain("margin-top: auto;");
    expect(globalStyles).not.toContain("bottom: 16px;\n  left: 16px;");
  });

  it("keeps mobile sidebar quick actions compact before page content", () => {
    expect(globalStyles).toContain("@media (max-width: 640px)");
    expect(globalStyles).toContain("grid-template-columns: repeat(auto-fit, minmax(168px, 1fr));");
    expect(globalStyles).toContain(".sidebar-quick-action-grid {\n    display: flex;");
    expect(globalStyles).toContain("overflow-x: auto;");
    expect(globalStyles).toContain("overscroll-behavior-x: contain;");
    expect(globalStyles).toContain("-webkit-overflow-scrolling: touch;");
    expect(globalStyles).toContain(".sidebar-quick-actions a {\n    flex: 0 0 190px;");
  });

  it("browser smoke verifies the Settings link is visible and usable from the app shell", () => {
    expect(smokeSpec).toContain("sidebar-settings-link");
    expect(smokeSpec).toContain("Expected Settings shortcut to be visible in the app shell");
    expect(smokeSpec).toContain("await settingsShortcut.click()");
  });
});
